### ISSUE TITLE
Start using Sonarcloud

### ISSUE THREAD

**Issue by marcluque** [Benzammour/cretro#14]
Sonarcloud offers free static analysis for open-source projects. There is a setup tutorial for CMake/make based projects that runs with GitHub Actions. It certainly is worthwhile looking into.

**Comment by marcluque** [comment]
I think that sonarcloud needs to be setup by the repository owner or a an explicitly added contributor iirc.

**Comment by s3mme** [comment]
Closing this, as it was implemented!
